version: '3.0'
services:
  # VGG19 模型 server容器
  image-feature-vector:
    #image: image-feature-vector:latest
    # 首次运行时候使用如下命令构建镜像
    container_name: image-feature-vector
    build:
      context: ./image-feature-vector
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      TZ: Asia/Shanghai
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  # ES-8.0
  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # 设置集群名称
      cluster.name: elasticsearch-8.0
      # 以单一节点模式启动
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  #对象存储minio
  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    container_name: minio
    ports:
      # api 端口
      - "9000:9000"
      # 控制台端口
      - "9001:9001"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: minioadmin
      # 管理后台密码，最小8个字符
      MINIO_ROOT_PASSWORD: minioadmin
      # https需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      # 映射当前目录下的data目录至容器内/data目录
      - ./minio/data:/data
      # 映射配置目录
      - ./minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  #应用容器后端服务
  search_by_image:
    #image: search_by_image:latest
    # 首次运行时候使用如下命令构建镜像
    container_name: search_by_image
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - image-feature-vector
      - elasticsearch
      - minio
    networks:
      app_net:
        ipv4_address: 172.16.238.13

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1